base: core24
name: freeplane-mindmapping
summary: Application for Mind Mapping, Knowledge and Project Management
description: |
  Application for Mind Mapping, Knowledge Management, Project Management.
  Develop, organize and communicate your ideas and knowledge in the most
  effective way.

  Features
  - Mind Mapping
  - Knowledge Management
  - Project Management
  - Presentation
  - Outline
  - Writing

  Homepage: https://www.freeplane.org

confinement: strict
grade: stable
icon: data/gui/freeplane.png
adopt-info: freeplane-mindmapping

apps:
  freeplane-mindmapping:
    command: bin/desktop-launch $SNAP/freeplane/freeplane.sh
    plugs: 
      - cups-control
      - desktop
      - desktop-legacy
      - home
      - network
      - x11
    environment:
      _JAVA_OPTIONS: -Duser.home=$SNAP_USER_DATA 
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64
      FREEPLANE_JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64
      PATH: $SNAP/usr/lib/jvm/java-17-openjdk-amd64/bin:$SNAP/usr/lib/jvm/java-17-openjdk-amd64/jre/bin:$PATH

parts:
  desktop-glib:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - adwaita-icon-theme
      - dmz-cursor-theme
      - gnome-themes-ubuntu
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-0
      - libxkbcommon0
      - light-themes
      - locales-all
      - shared-mime-info
      - fonts-ubuntu
      - xdg-user-dirs

  freeplane-mindmapping:
    after: [desktop-glib]
    plugin: nil
    source: .
    override-build: |
      mkdir -p  $SNAPCRAFT_PART_INSTALL/meta/gui
      unzip freeplane*.zip -d $SNAPCRAFT_PART_INSTALL/
      mv $SNAPCRAFT_PART_INSTALL/freeplane-* $SNAPCRAFT_PART_INSTALL/freeplane
      chmod +x $SNAPCRAFT_PART_INSTALL/freeplane/freeplane.sh
      cp ./data/gui/* $SNAPCRAFT_PART_INSTALL/meta/gui/
      craftctl set version=$(ls freeplane*.zip|sed 's/.*-\([^-]\+\).zip/\1/'|tr -s '_' '-')
    build-packages:
      - unzip
    stage-packages:
      - openjdk-17-jre